"""
Loop 4 tests: Data Dictionary consistency with the SQLite `series` table.

The dict in docs/DATA_DICTIONARY.md was hand/magic-generated by "Loop A2" and
is stale (predates Loops 1-3): fx_fwd:AN was listed as derived/unknown even
though Loop 1 reclassified it to raw and sync_metadata backfilled its unit to
CNY/USD. This module gates the new generator (scripts/gen_data_dictionary.py)
and the committed dict it produces.

Verifies (real cross-checks: parse the markdown, then query the DB for the
expected values — never a tautology):
  1. The committed docs/DATA_DICTIONARY.md: fx_fwd:AN row matches the DB
     (series_type=raw, unit=CNY/USD).  -> RED against the stale dict.
  2. The committed dict contains EVERY chart-critical series_id from
     chart_catalog.json.
  3. The generator (gen_data_dictionary.generate) produces a dict whose
     fx_fwd:AN row matches the DB.  -> RED until the generator exists.
  4. The generator's output includes every chart-critical series_id.

The generator tests (3, 4) run the generator INSIDE the fixture so the test
stays green when the DB changes legitimately — it is the gate that the
generator is correct, not a check on a frozen file.
"""
import sys
import json
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

DB = ROOT / "data" / "monthly_brief.sqlite"
DICT_PATH = ROOT / "docs" / "DATA_DICTIONARY.md"
CHART_CAT = ROOT / "config" / "chart_catalog.json"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_db():
    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    return conn


def _chart_critical_sids():
    """Set of series_ids referenced by any chart in chart_catalog.json
    (datasets + scatter x/y), mirroring gen_status_docs.stats()."""
    cat = json.load(open(CHART_CAT, encoding="utf-8"))
    sids = set()
    for md in cat["modules"].values():
        for ch in md["charts"]:
            for ds in ch["datasets"]:
                sids.add(ds["series_id"])
            if ch.get("scatter"):
                sids.add(ch["scatter_x"]["series_id"])
                sids.add(ch["scatter_y"]["series_id"])
    return sids


def _parse_series_rows(md_text):
    """Parse the per-series markdown table rows into
    {series_id: {display_name, type, frequency, unit}}.

    A data row looks like:
        | fx_fwd:AN | USDCNY | raw | monthly | CNY/USD |
    Header/separator rows (| series_id | ... | or |---|---|) are skipped.
    """
    rows = {}
    for line in md_text.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        if "series_id" in line and "display_name" in line:
            continue  # header
        if set(line.replace("|", "").strip()) <= set("-: "):
            continue  # separator row
        parts = [p.strip() for p in line.strip("|").split("|")]
        if len(parts) != 5:
            continue
        sid = parts[0]
        # a real series_id always contains a colon (module:column); skip
        # any stray non-series row (e.g. summary table rows have 2 cols).
        if ":" not in sid:
            continue
        rows[sid] = {
            "display_name": parts[1],
            "type": parts[2],
            "frequency": parts[3],
            "unit": parts[4],
        }
    return rows


def _db_series_row(conn, sid):
    r = conn.execute(
        "SELECT series_id, display_name, series_type, frequency, unit "
        "FROM series WHERE series_id=?",
        (sid,),
    ).fetchone()
    return dict(r) if r else None


def _unit_as_dict_shows(db_unit):
    """How the generator renders a DB unit in the markdown (None/empty->unknown)."""
    if db_unit is None or str(db_unit).strip() == "":
        return "unknown"
    return str(db_unit)


# ---------------------------------------------------------------------------
# Committed dict (RED against the stale file)
# ---------------------------------------------------------------------------

def test_committed_dict_fx_fwd_an_matches_db():
    """The committed docs/DATA_DICTIONARY.md fx_fwd:AN row must match the DB.
    Fails RED on the stale dict (which shows derived/unknown)."""
    conn = _get_db()
    committed = DICT_PATH.read_text(encoding="utf-8")
    rows = _parse_series_rows(committed)
    db = _db_series_row(conn, "fx_fwd:AN")
    conn.close()
    assert db is not None, "fx_fwd:AN missing from DB"
    assert "fx_fwd:AN" in rows, "fx_fwd:AN missing from committed DATA_DICTIONARY.md"
    assert rows["fx_fwd:AN"]["type"] == db["series_type"], (
        f"fx_fwd:AN type stale: dict={rows['fx_fwd:AN']['type']!r} "
        f"db={db['series_type']!r}"
    )
    assert rows["fx_fwd:AN"]["unit"] == _unit_as_dict_shows(db["unit"]), (
        f"fx_fwd:AN unit stale: dict={rows['fx_fwd:AN']['unit']!r} "
        f"db={db['unit']!r}"
    )
    # Explicit expectations (the Loop 1 corrections):
    assert rows["fx_fwd:AN"]["type"] == "raw", (
        f"fx_fwd:AN must be raw (Loop 1), got {rows['fx_fwd:AN']['type']!r}"
    )
    assert rows["fx_fwd:AN"]["unit"] == "CNY/USD", (
        f"fx_fwd:AN must be CNY/USD, got {rows['fx_fwd:AN']['unit']!r}"
    )


def test_committed_dict_has_all_chart_critical_sids():
    """Every chart-critical series_id must be present in the committed dict."""
    committed = DICT_PATH.read_text(encoding="utf-8")
    rows = _parse_series_rows(committed)
    missing = _chart_critical_sids() - set(rows)
    assert not missing, (
        f"chart-critical sids missing from committed DATA_DICTIONARY.md: "
        f"{sorted(missing)}"
    )


# ---------------------------------------------------------------------------
# Generator gate (verifies scripts/gen_data_dictionary.py is correct)
# ---------------------------------------------------------------------------

def test_generator_fx_fwd_an_matches_db():
    """The generator output's fx_fwd:AN row must match the DB."""
    import gen_data_dictionary as gdd  # RED until the module exists
    conn = _get_db()
    md = gdd.generate(conn)
    conn.close()
    rows = _parse_series_rows(md)
    db = _db_series_row(_get_db(), "fx_fwd:AN")
    assert "fx_fwd:AN" in rows, "fx_fwd:AN missing from generated dict"
    assert rows["fx_fwd:AN"]["type"] == db["series_type"], (
        f"generator fx_fwd:AN type: dict={rows['fx_fwd:AN']['type']!r} "
        f"db={db['series_type']!r}"
    )
    assert rows["fx_fwd:AN"]["unit"] == _unit_as_dict_shows(db["unit"]), (
        f"generator fx_fwd:AN unit: dict={rows['fx_fwd:AN']['unit']!r} "
        f"db={db['unit']!r}"
    )


def test_generator_includes_all_chart_critical_sids():
    """The generator output must include every chart-critical series_id."""
    import gen_data_dictionary as gdd  # RED until the module exists
    conn = _get_db()
    md = gdd.generate(conn)
    conn.close()
    rows = _parse_series_rows(md)
    missing = _chart_critical_sids() - set(rows)
    assert not missing, (
        f"chart-critical sids missing from generated dict: {sorted(missing)}"
    )
