"""
gen_data_dictionary.py — Generate docs/DATA_DICTIONARY.md directly from the
SQLite `series` table (single source of truth).

Loop 4: replaces the stale hand/magic-generated dict produced by "Loop A2".
Every count in the Summary and every per-series row is computed live from the
`series` (and `observations`) tables — no hard-coded numbers, so the dict can
never drift from the DB again. The committed file is regenerated by running:

    python3 scripts/gen_data_dictionary.py

The generator is gated by tests/test_data_dictionary.py, which runs
`generate(conn)` inside the fixture and cross-checks the parsed output
against the DB (so the test stays green when the DB changes legitimately).
"""
import sqlite3
from datetime import datetime
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent
DB = ROOT / "data" / "monthly_brief.sqlite"
OUT = ROOT / "docs" / "DATA_DICTIONARY.md"


def _unit_label(u):
    """Render a DB unit for the markdown table; NULL/empty -> 'unknown'."""
    if u is None or str(u).strip() == "":
        return "unknown"
    return str(u)


def stats(conn):
    """Live-computed summary counts. No hard-coded numbers."""
    s = {}
    s["total"] = conn.execute("SELECT COUNT(*) FROM series").fetchone()[0]
    s["by_type"] = dict(
        Counter(r[0] for r in conn.execute("SELECT series_type FROM series"))
    )
    s["with_obs"] = conn.execute(
        "SELECT COUNT(DISTINCT series_id) FROM observations WHERE value IS NOT NULL"
    ).fetchone()[0]
    dr = conn.execute(
        "SELECT MIN(date), MAX(date) FROM observations WHERE value IS NOT NULL"
    ).fetchone()
    s["date_min"] = dr[0]
    s["date_max"] = dr[1]
    s["column_star"] = conn.execute(
        "SELECT COUNT(*) FROM series WHERE display_name LIKE 'Column_%'"
    ).fetchone()[0]
    s["unknown_unit"] = conn.execute(
        "SELECT COUNT(*) FROM series WHERE unit IS NULL OR unit='' OR unit='unknown'"
    ).fetchone()[0]
    return s


def generate(conn, generated_at=None):
    """Return the DATA_DICTIONARY.md markdown as a string.

    `conn` must have row_factory set to sqlite3.Row (callers using a plain
    connection should set it first; main() does). `generated_at` is injected
    only to make the timestamp deterministic in tests.
    """
    if generated_at is None:
        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    s = stats(conn)
    modules = [
        r[0] for r in conn.execute(
            "SELECT DISTINCT module FROM series ORDER BY module"
        )
    ]

    lines = []
    lines.append("# Data Dictionary")
    lines.append("")
    lines.append(
        "> Auto-generated from SQLite `series` table by `gen_data_dictionary.py`"
    )
    lines.append(f"> Generated: {generated_at}")
    lines.append("> Single source of truth: `data/monthly_brief.sqlite` · `series` table")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Series (SQLite) | {s['total']} |")
    lines.append(f"| Raw | {s['by_type'].get('raw', 0)} |")
    lines.append(f"| Derived | {s['by_type'].get('derived', 0)} |")
    lines.append(f"| Manual | {s['by_type'].get('manual', 0)} |")
    lines.append(f"| With Observations | {s['with_obs']} |")
    lines.append(f"| Time Range | {s['date_min']} → {s['date_max']} |")
    lines.append(f"| Column_* (Excel intermediate) | {s['column_star']} |")
    lines.append(f"| Unknown / empty unit | {s['unknown_unit']} |")
    lines.append("")
    lines.append("## Known Issues")
    lines.append("")
    lines.append(
        f"- **{s['column_star']}** series still named `Column_*` "
        "(Excel intermediate columns; out of v1 display scope, retained in DB)."
    )
    lines.append(
        f"- **{s['unknown_unit']}** series with empty/unknown units "
        "(primarily DB-only intermediates; chart-critical series all have a real unit)."
    )
    lines.append(
        "- `fx_fwd:AN` (USDCNY): raw external seed rate (`source=excel_seed`), "
        "history from an Excel VLOOKUP FX-rate lookup table; pending Wind "
        "USDCNY monthly-rate mapping."
    )
    lines.append("")
    lines.append("## Series by Module")
    lines.append("")
    for mod in modules:
        rows = conn.execute(
            "SELECT series_id, display_name, series_type, frequency, unit "
            "FROM series WHERE module=? ORDER BY series_id",
            (mod,),
        ).fetchall()
        lines.append(f"### {mod} ({len(rows)} series)")
        lines.append("")
        lines.append("| series_id | display_name | type | frequency | unit |")
        lines.append("|-----------|-------------|------|-----------|------|")
        for r in rows:
            sid, dn, st, freq, unit = r
            freq = freq or "unknown"
            lines.append(
                f"| {sid} | {dn} | {st} | {freq} | {_unit_label(unit)} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    md = generate(conn)
    conn.close()
    OUT.write_text(md, encoding="utf-8")
    print(f"Generated {OUT.relative_to(ROOT)}")
    s = stats(sqlite3.connect(DB))
    print(
        f"  series={s['total']} (raw {s['by_type'].get('raw',0)}/"
        f"derived {s['by_type'].get('derived',0)}/manual {s['by_type'].get('manual',0)}) "
        f"with_obs={s['with_obs']} column_*={s['column_star']} unknown_unit={s['unknown_unit']}"
    )


if __name__ == "__main__":
    main()
